## Pandas Tutorial

Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

Agenda

- What is Data Frames?
- What is Data Series?
- Different operation in Pandas

In [ ]:
## First step is to import pandas

import pandas as pd
import numpy as np

In [ ]:
## Creating Dataframe

df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=["Column1","Column2","Column3","Column4"])

In [ ]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [ ]:
df[['Column2', 'Column3']]

Column2  Column3
Row1        1        2
Row2        5        6
Row3        9       10
Row4       13       14
Row5       17       18

### loc - loc is label-based, which means that you have to specify rows and columns based on their row and column labels

### iloc (index location) - iloc is integer position-based, so you have to specify rows and columns by their integer position values (0-based integer position)

In [ ]:
## Accessing the elements

df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [ ]:
## Check the type

type(df.loc['Row1'])

pandas.core.series.Series

In [ ]:
df.iloc[:,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
## Take the elements from the Column2
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [ ]:
#convert Dataframes into array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [ ]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [ ]:
df['Column1'].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: Column1, dtype: int64

In [ ]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [ ]:
df=pd.read_csv('mercedesbenz.csv')

In [ ]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [ ]:
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [ ]:
#Get the unique category counts
df['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
i      18
aq     18
am     18
u      17
l      16
aw     16
ad     14
au     11
b      11
k      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
ab      1
g       1
Name: X0, dtype: int64

In [ ]:
df[df['y']>100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

In [ ]:
df.corr()

ID         y       X10  X11       X12       X13       X14  \
ID    1.000000 -0.055108  0.001602  NaN  0.058988 -0.031917 -0.025438   
y    -0.055108  1.000000 -0.026985  NaN  0.089792  0.048276  0.193643   
X10   0.001602 -0.026985  1.000000  NaN -0.033084 -0.028806 -0.100474   
X11        NaN       NaN       NaN  NaN       NaN       NaN       NaN   
X12   0.058988  0.089792 -0.033084  NaN  1.000000  0.214825 -0.246513   
...        ...       ...       ...  ...       ...       ...       ...   
X380 -0.013577  0.040932 -0.010479  NaN -0.005566  0.023045  0.007743   
X382 -0.038171 -0.159815 -0.010164  NaN -0.024937 -0.021713  0.012713   
X383 -0.009332  0.040291 -0.004740  NaN -0.011628 -0.010125  0.023604   
X384 -0.015355 -0.004591 -0.002532  NaN -0.006212  0.041242  0.025199   
X385  0.029059 -0.022280 -0.004387  NaN -0.010765 -0.009373  0.043667   

           X15       X16       X17  ...      X375      X376      X377  \
ID    0.002237 -0.036480 -0.038171  ...  0.045229 -0.080259 -0.022965   
y     0.023116  0.048946 -0.159815  ...  0.029100  0.114005  0.061403   
X10  -0.002532 -0.005944 -0.010164  ...  0.165277 -0.028618 -0.074244   
X11        NaN       NaN       NaN  ...       NaN       NaN       NaN   
X12  -0.006212 -0.014584 -0.024937  ... -0.107864 -0.070214  0.030134   
...        ...       ...       ...  ...       ...       ...       ...   
X380 -0.001968 -0.004619 -0.007899  ... -0.061741 -0.022240 -0.061168   
X382 -0.001908 -0.004480  1.000000  ... -0.059883 -0.021571 -0.059327   
X383 -0.000890 -0.002089 -0.003572  ... -0.015413 -0.010059  0.035107   
X384 -0.000475 -0.001116 -0.001908  ... -0.014917 -0.005373  0.008694   
X385 -0.000824 -0.001934 -0.003307  ...  0.055225 -0.009311 -0.025610   

          X378      X379      X380      X382      X383      X384      X385  
ID    0.030371  0.023382 -0.013577 -0.038171 -0.009332 -0.015355  0.029059  
y    -0.258679  0.067919  0.040932 -0.159815  0.040291 -0.004591 -0.022280  
X10  -0.016870 -0.011374 -0.010479 -0.010164 -0.004740 -0.002532 -0.004387  
X11        NaN       NaN       NaN       NaN       NaN       NaN       NaN  
X12  -0.016043 -0.027907 -0.005566 -0.024937 -0.011628 -0.006212 -0.010765  
...        ...       ...       ...       ...       ...       ...       ...  
X380 -0.013110 -0.008839  1.000000 -0.007899 -0.003683 -0.001968 -0.003410  
X382 -0.012716 -0.008573 -0.007899  1.000000 -0.003572 -0.001908 -0.003307  
X383 -0.005930 -0.003998 -0.003683 -0.003572  1.000000 -0.000890 -0.001542  
X384 -0.003168 -0.002136 -0.001968 -0.001908 -0.000890  1.000000 -0.000824  
X385 -0.005489 -0.003701 -0.003410 -0.003307 -0.001542 -0.000824  1.000000  

[370 rows x 370 columns]

In [ ]:
df['X11'].value_counts()

0    4209
Name: X11, dtype: int64

In [ ]:
import numpy as np

In [ ]:
lst_data=[[1,2,3],[3,4,np.nan],[5,6,np.nan],[np.nan,np.nan,np.nan]]
lst_data

[[1, 2, 3], [3, 4, nan], [5, 6, nan], [nan, nan, nan]]

In [ ]:
df=pd.DataFrame(lst_data)

In [ ]:
df.head()

0    1    2
0  1.0  2.0  3.0
1  3.0  4.0  NaN
2  5.0  6.0  NaN
3  NaN  NaN  NaN

In [ ]:
## HAndling Missing Values

##Drop nan values

df.dropna(axis=0)

0    1    2
0  1.0  2.0  3.0

In [ ]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [ ]:
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f', 'h'],
                     columns=['one', 'two', 'three'])

In [ ]:
df.head()

one       two     three
a -1.916735 -0.173240  1.367206
c  1.312738 -2.141986  0.542119
e  0.892091 -0.122928 -0.676124
f -0.448301  0.017504 -0.153914
h  0.150060 -0.020558  1.374107

In [ ]:
df2=df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [ ]:
df2

one       two     three
a -1.916735 -0.173240  1.367206
b       NaN       NaN       NaN
c  1.312738 -2.141986  0.542119
d       NaN       NaN       NaN
e  0.892091 -0.122928 -0.676124
f -0.448301  0.017504 -0.153914
g       NaN       NaN       NaN
h  0.150060 -0.020558  1.374107

In [ ]:
df2.dropna(axis=0)

one       two     three
a -1.916735 -0.173240  1.367206
c  1.312738 -2.141986  0.542119
e  0.892091 -0.122928 -0.676124
f -0.448301  0.017504 -0.153914
h  0.150060 -0.020558  1.374107

In [ ]:
pd.isna(df2['one'])

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

In [ ]:
df2['one'].notna()

a     True
b    False
c     True
d    False
e     True
f     True
g    False
h     True
Name: one, dtype: bool

In [ ]:
df2.fillna('Missing')

one        two     three
a  -1.91674   -0.17324   1.36721
b   Missing    Missing   Missing
c   1.31274   -2.14199  0.542119
d   Missing    Missing   Missing
e  0.892091  -0.122928 -0.676124
f -0.448301  0.0175044 -0.153914
g   Missing    Missing   Missing
h   0.15006 -0.0205578   1.37411

In [ ]:
df2['one'].values

array([-1.91673531,         nan,  1.31273752,         nan,  0.89209108,
       -0.44830066,         nan,  0.15006008])

In [ ]:
### Reading different data sources with the help of pandas

## CSV

In [ ]:
from io import StringIO, BytesIO

In [ ]:
data = ('col1,col2,col3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')
data

'col1,col2,col3\nx,y,1\na,b,2\nc,d,3'

In [ ]:
type(data)

str

In [ ]:
StringIO()

In [ ]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [ ]:
df=pd.read_csv(StringIO(data), usecols=['col1', 'col3'])
df

col1  col3
0    x     1
1    a     2
2    c     3

In [ ]:
## Read from specific columns
df=pd.read_csv(StringIO(data), usecols=lambda x: x.upper() in ['COL1', 'COL3'])

In [ ]:
df.to_csv('Test.csv')

In [ ]:
## Specifying columns data types

data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11')


In [ ]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11


In [ ]:
df=pd.read_csv(StringIO(data),dtype=object)

In [ ]:
df

a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [ ]:
df['a'][1]

'5'

In [ ]:
df=pd.read_csv(StringIO(data),dtype={'b':int,'c':np.float,'a':'Int64'})

In [ ]:
df

a   b     c    d
0  1   2   3.0  4.0
1  5   6   7.0  8.0
2  9  10  11.0  NaN

In [ ]:
df['a'][1]

5

In [ ]:
## check the datatype
df.dtypes

a      Int64
b      int32
c    float64
d    float64
dtype: object

In [ ]:
## Index columns and training delimiters


In [ ]:
data = ('index,a,b,c\n'
           '4,apple,bat,5.7\n'
            '8,orange,cow,10')

In [1]:
## Assignment - Explore this dataset using pandas...

df=pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',
                 sep='\t')

NameError: ignored

In [ ]:
df